apiVersion: v1
kind: Pod
metadata:
  name: devboard-frontend
  namespace: devboard

spec:
  containers:
  - name: frontend
    image: salaskaraniket/devboard-frontend
    ports:
    - containerPort: 4173



